title: Amalik on Github lab
author: Amalik Amriou
email: amalik@amalikamriou.com
theme : minima
description: > # this means to ignore newlines until "baseurl:"
  C'est la description

# social links
twitter_username: amalik
github_username:  amalik
show_excerpts: true # set to false to remove excerpts on the homepage
